name: Labeling new issue
on:
  issues:
      types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2 # or v2.1.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: false
          labels-synonyms: '{"question":["?"],"bug":["break","bug","issue","problem"],"enhancement":["add","feature","features"]}'
          labels-not-allowed: '["duplicate","hacktoberfest-accepted","level-1","level-2","wontfix"]'
          default-labels: '["hacktoberfest"]'
